### ISSUE TITLE
2D繪圖_手繪漸開線齒輪

### ISSUE THREAD

**Issue by 40223229** [40223229/2015cdb_g9#7]

**Comment by 2014cdbg4** [comment]
陳令宛嗨~~~<<<是這樣嗎?!

**Comment by 2014cdbg4** [comment]
2D繪圖是要在哪裡呈現?!

**Comment by 40223229** [comment]
先在近端使用brython測試
有成果後 再送到openshift呈現

**Comment by 40123135** [comment]
讓組員了解參數化正齒輪的繪製原理，以及各段程式碼所對應的的齒型曲線(齒頂圓、漸開線、齒底圓)
再著手進行尺寸更改的部分
最終目的為：使用者只需輸入模數、齒數、壓力角等數據，即可生成一正齒輪。
